package com.dragnon.consoleapp;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;

// Generated by Spring Initializr (https://start.spring.io)
//@SpringBootApplication
//public class ConsoleappApplication {
//
//	public static void main(String[] args) {
//		SpringApplication.run(ConsoleappApplication.class, args);
//	}
//
//}

// An alternative implementation
public class ConsoleappApplication
        implements CommandLineRunner {

    private static final Logger LOG = LoggerFactory.getLogger(ConsoleappApplication.class);

    public static void main(String[] args) {
        LOG.info("STARTING THE APPLICATION");
        SpringApplication.run(ConsoleappApplication.class, args);
        LOG.info("APPLICATION FINISHED");
    }

    @Override
    public void run(String... args) {
        LOG.info("EXECUTING : command line runner");

        for (int i = 0; i < args.length; ++i) {
            LOG.info("args[{}]: {}", i, args[i]);
        }
    }
}
